modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Extract%20Poison"
logoFile="icon.png"

[[mods]]
modId="extractpoison"
version="3.1"
displayName="Extract Poison"
displayURL="https://curseforge.com/minecraft/mc-mods/extract-poison"
authors="Rick South"
description='''Allows the extraction of poison from cave spiders, pufferfish and bees with an empty bottle.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.extractpoison]]
    modId="collective"
    mandatory=true
    versionRange="[6.45,)"
    ordering="NONE"
    side="BOTH"